import { Router } from 'express';
import authRoutes from './authRoutes';
import blogRoutes from './blogRoutes';
import contactRoutes from './contactRoutes';
import customerRoutes from './customerRoutes';
import dashboardRoutes from './dashboardRoutes';
import galleryRoutes from './galleryRoutes';
import healthRoutes from './healthRoutes';
import leadRoutes from './leadRoutes';
import { templatesRouter, profilesRouter } from './measurementRoutes';
import orderRoutes from './orderRoutes';
import portalRoutes, { adminPortalExtrasRouter } from './portalRoutes';
import portfolioRoutes from './portfolioRoutes';
import productCatalogRoutes from './productCatalogRoutes';
import serviceRoutes from './serviceRoutes';
import settingsRoutes from './settingsRoutes';
import adminSettingsRoutes from './adminSettingsRoutes';
import { createSlugAvailableRouter } from './slugAvailableRoutes';
import uploadRoutes from './uploadRoutes';
import staffRoutes from './staffRoutes';
import financeRoutes from './financeRoutes';
import reportRoutes from './reportRoutes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/contact', contactRoutes);
router.use('/portal', portalRoutes);
router.use('/admin/portal', adminPortalExtrasRouter);
router.use('/admin/dashboard', dashboardRoutes);
router.use('/admin/customers', customerRoutes);
router.use('/admin/orders', orderRoutes);
router.use('/admin/products', productCatalogRoutes);
router.use('/admin/staff', staffRoutes);
router.use('/admin/finance', financeRoutes);
router.use('/admin/reports', reportRoutes);
router.use('/admin/settings', adminSettingsRoutes);
router.use('/admin', createSlugAvailableRouter());
router.use('/gallery', galleryRoutes);
router.use('/services', serviceRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/blogs', blogRoutes);
router.use('/leads', leadRoutes);
router.use('/measurement-templates', templatesRouter);
router.use('/measurements', profilesRouter);
router.use('/upload', uploadRoutes);
router.use('/settings', settingsRoutes);

export default router;
